<a href="https://colab.research.google.com/github/ersharadpal/python/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import time

In [ ]:
a=[10,20,30]
start=time.time()

for i in a:
  print(i)

end=time.time()

total_time=end-start
print(total_time)

10
20
30
0.00023627281188964844


In [ ]:
a= range(10)

In [ ]:
a= list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

In [ ]:

#arr=np.array([1,3,4])
arr=np.array ([[[]]])
arr.dtype

dtype('float64')

In [ ]:
arr.ndim

3

In [ ]:
a=list(range(10))
b=list(range(10))

c=[]

for i in range (len(a)):
  x=a[1]+b[i]
  c.append(x)
print(c)

#print(time.time(-start))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
d=np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=list(range(10))
b=list(range(10))

start=time.time()
c=[a[i] + b[i] for i in range(len(a))]

print(time.time()-start)

0.0001819133758544922


In [ ]:
import numpy as np
import time

a=np.arange(100000)
b=np.arange(100000)

start=time.time()

c=a+b

print(time.time()-start )

0.0006573200225830078


In [ ]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
np.arange(5,-10,-2)


array([ 5,  3,  1, -1, -3, -5, -7, -9])

In [ ]:
np.linspace(10,100)

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [ ]:
np.linspace(10,100,2)

array([ 10., 100.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
import sys

lst=list(range(1000))

arr=np.array(range(1000))

sys.getsizeof(lst)

arr.nbytes

8000

In [ ]:
a = np.array([1,3,4,5],dtype= float)
b = np.array([1,3,4,6],dtype = "int")

c=a+b
print(c)


[ 2.  6.  8. 11.]


In [ ]:
np.array([1,3,4,5]).dtype

dtype('int64')

In [ ]:
list=[ [1,2,3],
      [4,6,7]]

arr=np.array(list)
arr.ndim
arr.shape
print(arr)

[[1 2 3]
 [4 6 7]]


In [ ]:
list=[ [1,2,np.nan,3],  # same structure for input , for zero we pass none, np.nan or nan
      [4,6,7]]

arr=np.array(list)

arr.ndim
arr.shape


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr2=np.array([[2,2],[2,2]])
x=np.eye(2)

d = arr2/x

print(d)

[[ 2. inf]
 [inf  2.]]


/tmp/ipython-input-996213609.py:4: RuntimeWarning: divide by zero encountered in divide
  d = arr2/x


In [ ]:
arr2=np.array([[2,3],[4,5]])
arr

In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
# mat[0,0]
# mat[1,2]
# mat[:,1]
mat[1,:]

array([4, 5, 6])

In [ ]:
arr[(arr>10) & (arr<40)]


array([], dtype=int64)

In [ ]:
arr=np.arange([[1,13],[4,5]])
x=arr2.flatten()
x[1:3]
arr2=x.reshape(2,4)

arr2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
import random
a=random.randit(5,10)
print(a)

AttributeError: module 'random' has no attribute 'randit'

In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])

v_stacked=np.vstack((a,b))

print(v_stacked)
v_stacked.ndim


[[1 2 3]
 [4 5 6]]


2

In [ ]:
a= np.array([1,2,3])
b= np.array([4,5,6])

h_stacked=np.hstack((a,b))

print(h_stacked)
h_stacked.ndim

[1 2 3 4 5 6]


1